type CategoryLabels = {
  [key: string]: string; // 모든 문자열 키는 문자열 값을 가집니다.
};

export const tierColorMap: Record<string, string> = {
  "S+": "bg-green-100",
  S: "bg-green-200",
  "A+": "bg-blue-100",
  A: "bg-blue-200",
  "B+": "bg-yellow-100",
  B: "bg-yellow-200",
  C: "bg-red-100",
  D: "bg-red-200",
};

export const categoryLabels: CategoryLabels = {
  forum: "자유게시판",
  support: "클랜 후원",
  introduce: "가입인사",
  feedback: "건의사항",
  tactics: "전략전술",
  dailycheckin: "출석체크",
  ranking: "랭킹전",
  event: "이벤트",
  opponent: "외부리그",
  versus: "끝장전",
  notice: "공지사항",
  proleaguenotice: "프로리그",
  beforetear: "티어배정신청",
  aftertear: "티어배정완료",
  vod: "VOD",
};

export const getCategoryPath = (category: string) => {
  switch (category) {
    case "공지사항":
      return "/clanbe/notices";
    case "클랜 후원":
      return "/clanbe/support";
    case "자유게시판":
      return "/community/forum";
    case "가입인사":
      return "/community/introduce";
    case "건의사항":
      return "/community/feedback";
    case "전략전술":
      return "/community/tactics";
    case "출석체크":
      return "/community/dailycheckin";
    case "랭킹전":
      return "/league/ranking";
    case "이벤트":
      return "/league/event";
    case "외부리그":
      return "/league/opponent";
    case "끝장전":
      return "/league/versus";
    case "VOD":
      return "/league/vod";
    case "프로리그":
      return "/proleague/notice";
    default:
      return "/"; // 기본 경로
  }
};

export const column = [
  { name: "닉네임", uid: "nickname", sortable: true },
  { name: "종족", uid: "race", sortable: true },
  { name: "승", uid: "wins", sortable: true },
  { name: "패", uid: "losses", sortable: true },
  { name: "BELO", uid: "belo" },
];

export const statusOptions = [
  { name: "Active", uid: "active" },
  { name: "Paused", uid: "paused" },
  { name: "Vacation", uid: "vacation" },
];

export const playersData = [
  { nickname: "Hope", race: "p", wins: 68, losses: 9, belo: 1735 },
  { nickname: "AT", race: "z", wins: 14, losses: 4, belo: 1641 },
  { nickname: "Song", race: "z", wins: 37, losses: 17, belo: 1621 },
  { nickname: "uNiQue", race: "t", wins: 11, losses: 7, belo: 1609 },
  { nickname: "Chojja", race: "p", wins: 9, losses: 6, belo: 1606 },
  { nickname: "Panda", race: "t", wins: 4, losses: 3, belo: 1602 },
  { nickname: "allfree", race: "z", wins: 2, losses: 0, belo: 1600 },
  { nickname: "needmonkey", race: "z", wins: 0, losses: 0, belo: 1600 },
  { nickname: "Sai", race: "z", wins: 0, losses: 0, belo: 1600 },
  { nickname: "Dulgi", race: "t", wins: 0, losses: 0, belo: 1600 },
  { nickname: "Astell", race: "p", wins: 22, losses: 16, belo: 1589 },
  { nickname: "Promise", race: "p", wins: 0, losses: 1, belo: 1589 },
  { nickname: "Sinma", race: "z", wins: 2, losses: 4, belo: 1586 },
  { nickname: "Marine", race: "t", wins: 2, losses: 9, belo: 1570 },
  { nickname: "TopGun", race: "t", wins: 9, losses: 10, belo: 1568 },
  { nickname: "Naerim", race: "t", wins: 9, losses: 7, belo: 1555 },
  { nickname: "4Vulture", race: "t", wins: 15, losses: 20, belo: 1514 },
  { nickname: "Careful", race: "z", wins: 11, losses: 26, belo: 1500 },
  { nickname: "Koeun", race: "p", wins: 42, losses: 38, belo: 1363 },
  { nickname: "Gravity", race: "p", wins: 0, losses: 0, belo: 1350 },
  { nickname: "Move", race: "z", wins: 4, losses: 1, belo: 1347 },
  { nickname: "Terran", race: "t", wins: 4, losses: 7, belo: 1345 },
  { nickname: "Gisas", race: "p", wins: 2, losses: 6, belo: 1341 },
  { nickname: "JMT", race: "t", wins: 9, losses: 14, belo: 1339 },
  { nickname: "Jeobji", race: "t", wins: 47, losses: 69, belo: 1219 },
  { nickname: "bebig", race: "p", wins: 40, losses: 32, belo: 1198 },
  { nickname: "Developer", race: "t", wins: 14, losses: 10, belo: 1180 },
  { nickname: "LAUFE", race: "p", wins: 26, losses: 6, belo: 1178 },
  { nickname: "Yoasobi", race: "z", wins: 20, losses: 6, belo: 1162 },
  { nickname: "GaeGgul", race: "p", wins: 5, losses: 3, belo: 1159 },
  { nickname: "Eunice", race: "t", wins: 3, losses: 5, belo: 1150 },
  { nickname: "CU", race: "p", wins: 1, losses: 1, belo: 1150 },
  { nickname: "Delluna", race: "p", wins: 5, losses: 5, belo: 1146 },
  { nickname: "Soo", race: "p", wins: 7, losses: 14, belo: 1138 },
  { nickname: "Wanja", race: "p", wins: 8, losses: 14, belo: 1125 },
  { nickname: "Zzz", race: "p", wins: 16, losses: 11, belo: 1119 },
  { nickname: "Politan", race: "t", wins: 33, losses: 20, belo: 1110 },
  { nickname: "mnb", race: "z", wins: 37, losses: 35, belo: 1097 },
  { nickname: "yodaking", race: "z", wins: 35, losses: 27, belo: 1079 },
  { nickname: "fOrU", race: "p", wins: 16, losses: 21, belo: 1069 },
  { nickname: "Jerry", race: "t", wins: 13, losses: 8, belo: 1058 },
  { nickname: "ShangKS", race: "t", wins: 6, losses: 9, belo: 1050 },
  { nickname: "Dark", race: "p", wins: 0, losses: 0, belo: 1050 },
  { nickname: "Mesis", race: "p", wins: 19, losses: 39, belo: 1047 },
  { nickname: "Quiet", race: "z", wins: 10, losses: 8, belo: 1016 },
  { nickname: "Ruin", race: "z", wins: 54, losses: 50, belo: 1014 },
  { nickname: "Paduk", race: "p", wins: 26, losses: 27, belo: 1002 },
  { nickname: "eByeong", race: "p", wins: 26, losses: 46, belo: 999 },
  { nickname: "Miniangma", race: "p", wins: 5, losses: 1, belo: 986 },
  { nickname: "dduk", race: "z", wins: 42, losses: 56, belo: 957 },
  { nickname: "LYJ", race: "t", wins: 5, losses: 0, belo: 957 },
  { nickname: "inbong", race: "p", wins: 10, losses: 5, belo: 950 },
  { nickname: "Promy", race: "t", wins: 2, losses: 5, belo: 950 },
  { nickname: "Taxer", race: "p", wins: 0, losses: 0, belo: 950 },
  { nickname: "Lonely", race: "t", wins: 0, losses: 0, belo: 950 },
  { nickname: "speed", race: "z", wins: 33, losses: 24, belo: 919 },
  { nickname: "NaNa", race: "p", wins: 13, losses: 10, belo: 912 },
  { nickname: "Gotz", race: "p", wins: 4, losses: 3, belo: 863 },
  { nickname: "Ting", race: "p", wins: 8, losses: 16, belo: 854 },
  { nickname: "Fighter", race: "t", wins: 2, losses: 3, belo: 853 },
  { nickname: "FATTY", race: "z", wins: 18, losses: 10, belo: 852 },
  { nickname: "Snow", race: "p", wins: 4, losses: 2, belo: 850 },
  { nickname: "Arin", race: "t", wins: 1, losses: 4, belo: 850 },
  { nickname: "Poo", race: "p", wins: 0, losses: 0, belo: 850 },
  { nickname: "Cause", race: "p", wins: 0, losses: 1, belo: 843 },
  { nickname: "omgYubin", race: "p", wins: 37, losses: 46, belo: 840 },
  { nickname: "bugaboo", race: "t", wins: 11, losses: 8, belo: 837 },
  { nickname: "anG", race: "z", wins: 11, losses: 27, belo: 832 },
  { nickname: "Tako", race: "p", wins: 41, losses: 51, belo: 830 },
  { nickname: "Cost", race: "z", wins: 35, losses: 43, belo: 820 },
  { nickname: "Josh", race: "p", wins: 11, losses: 3, belo: 813 },
  { nickname: "PlugPower", race: "t", wins: 40, losses: 37, belo: 809 },
  { nickname: "Hankukkwan", race: "z", wins: 10, losses: 3, belo: 789 },
  { nickname: "JB", race: "z", wins: 11, losses: 7, belo: 788 },
  { nickname: "to...K", race: "z", wins: 2, losses: 2, belo: 750 },
  { nickname: "Ark", race: "t", wins: 25, losses: 29, belo: 749 },
  { nickname: "chaboom", race: "z", wins: 2, losses: 3, belo: 749 },
  { nickname: "Captain", race: "p", wins: 21, losses: 28, belo: 736 },
  { nickname: "Light", race: "t", wins: 3, losses: 5, belo: 736 },
  { nickname: "Smart", race: "p", wins: 1, losses: 6, belo: 731 },
  { nickname: "GamJa", race: "z", wins: 16, losses: 22, belo: 726 },
  { nickname: "Cervix", race: "p", wins: 1, losses: 5, belo: 718 },
  { nickname: "Sugi", race: "p", wins: 28, losses: 35, belo: 710 },
  { nickname: "Medic", race: "t", wins: 14, losses: 8, belo: 709 },
  { nickname: "Debruybe", race: "t", wins: 4, losses: 14, belo: 705 },
  { nickname: "Mangnani", race: "z", wins: 2, losses: 2, belo: 653 },
  { nickname: "Hayun", race: "t", wins: 0, losses: 0, belo: 650 },
  { nickname: "Azure", race: "p", wins: 0, losses: 10, belo: 619 },
  { nickname: "Ssam", race: "t", wins: 2, losses: 2, belo: 28 },
  { nickname: "Apple", race: "t", wins: 26, losses: 13, belo: 1150 },
  { nickname: "ZZ", race: "p", wins: 0, losses: 0, belo: 1350 },
  { nickname: "HI", race: "z", wins: 0, losses: 0, belo: 950 },
  { nickname: "Name", race: "p", wins: 0, losses: 0, belo: "미지정" },
  { nickname: "Paranoize", race: "p", wins: 0, losses: 0, belo: "미지정" },
  { nickname: "Soft", race: "p", wins: 0, losses: 0, belo: "미지정" },
  { nickname: "DDuGi", race: "t", wins: 0, losses: 0, belo: "미지정" },
  { nickname: "hOn", race: "p", wins: 0, losses: 0, belo: "미지정" },
  { nickname: "Man", race: "z", wins: 0, losses: 0, belo: "미지정" },
  { nickname: "SqUAre", race: "z", wins: 0, losses: 3, belo: "미지정" },
];

export const beUsers = [
  {
    id: "laufe",
    nickname: "LAUFE",
    email: "sniperad@naver.com",
    name: "김도원",
    status: "승인",
    registrationDate: "2024-04-02",
    lastLogin: "2024-04-12",
    group: "관리그룹",
    actions: "조회/수정",
  },
  {
    id: "shinshin9914",
    nickname: "SnOw",
    email: "shinshin9914@naver.com",
    name: "신예준",
    status: "승인",
    registrationDate: "2022-02-26",
    lastLogin: "2024-03-06",
    group: "Member",
    actions: "조회/수정",
  },
  {
    id: "yodaking",
    nickname: "YODAKING",
    email: "kyh7008@nate.com",
    name: "김요환",
    status: "승인",
    registrationDate: "2022-02-24",
    lastLogin: "2024-04-16",
    group: ", Member",
    actions: "조회/수정",
  },
  {
    id: "apple",
    nickname: "Apple",
    email: "limhangeun@naver.com",
    name: "임한근",
    status: "승인",
    registrationDate: "2022-02-23",
    lastLogin: "2024-04-09",
    group: "Member",
    actions: "조회/수정",
  },
  {
    id: "chohaha",
    nickname: "Josh",
    email: "gatsumoto@naver.com",
    name: "조현영",
    status: "승인",
    registrationDate: "2022-02-16",
    lastLogin: "2024-04-08",
    group: "Member",
    actions: "조회/수정",
  },
  {
    id: "will1102",
    nickname: "Medic",
    email: "jisung991102@naver.com",
    name: "황지성",
    status: "승인",
    registrationDate: "2022-02-15",
    lastLogin: "2024-04-09",
    group: "Member",
    actions: "조회/수정",
  },
  {
    id: "dnrals804",
    nickname: "GamJa",
    email: "dnrals804@naver.com",
    name: "김욱민",
    status: "승인",
    registrationDate: "2022-02-13",
    lastLogin: "2024-04-30",
    group: "Member",
    actions: "조회/수정",
  },
  {
    id: "skyclub001",
    nickname: "WanJa",
    email: "lcw89@naver.com",
    name: "이찬우",
    status: "승인",
    registrationDate: "2022-02-13",
    lastLogin: "2024-04-16",
    group: "Member",
    actions: "조회/수정",
  },
  {
    id: "rlawogus5991",
    nickname: "Politan",
    email: "wogus6919@naver.com",
    name: "김재현",
    status: "승인",
    registrationDate: "2022-02-12",
    lastLogin: "2024-04-30",
    group: "Member",
    actions: "조회/수정",
  },
  {
    id: "zzz",
    nickname: "Zzz",
    email: "go_naa@naver.com",
    name: "이정우",
    status: "승인",
    registrationDate: "2022-02-12",
    lastLogin: "2024-04-18",
    group: "Member",
    actions: "조회/수정",
  },
  {
    id: "babo3267",
    nickname: "JB",
    email: "jung3267@naver.com",
    name: "한정빈",
    status: "승인",
    registrationDate: "2022-02-12",
    lastLogin: "2024-03-01",
    group: "Member",
    actions: "조회/수정",
  },
  {
    id: "gunhu123",
    nickname: "uNiQue",
    email: "nogunhu123@naver.com",
    name: "노건후",
    status: "승인",
    registrationDate: "2022-02-12",
    lastLogin: "2024-04-16",
    group: "Member",
    actions: "조회/수정",
  },
  {
    id: "nso1129",
    nickname: "OnSi",
    email: "nso_1129@hanmail.net",
    name: "남시온",
    status: "승인",
    registrationDate: "2022-02-12",
    lastLogin: "2023-01-15",
    group: "Member",
    actions: "조회/수정",
  },
  {
    id: "don1313",
    nickname: "Marine",
    email: "xkrwkdrns123@naver.com",
    name: "심기탁",
    status: "승인",
    registrationDate: "2022-02-12",
    lastLogin: "2024-04-25",
    group: "Member",
    actions: "조회/수정",
  },
  {
    id: "ksaml6061",
    nickname: "Promy",
    email: "ksaml6061@naver.com",
    name: "김경제",
    status: "승인",
    registrationDate: "2022-02-12",
    lastLogin: "2024-03-27",
    group: "Member",
    actions: "조회/수정",
  },
  {
    id: "corona7",
    nickname: "YOASOBI",
    email: "ryoko_@naver.com",
    name: "김원기",
    status: "승인",
    registrationDate: "2022-02-11",
    lastLogin: "2024-04-25",
    group: "Member",
    actions: "조회/수정",
  },
  {
    id: "cshocu6830",
    nickname: "Jerry",
    email: "tmdghqkfkrl@naver.com",
    name: "최승호",
    status: "승인",
    registrationDate: "2022-02-11",
    lastLogin: "2024-04-26",
    group: "Member",
    actions: "조회/수정",
  },
  {
    id: "dnlseldj7903",
    nickname: "soo",
    email: "esun829@naver.com",
    name: "엄익수",
    status: "승인",
    registrationDate: "2022-02-11",
    lastLogin: "2024-02-13",
    group: "Member",
    actions: "조회/수정",
  },
  {
    id: "gisa",
    nickname: "Gisa",
    email: "ggodoley@nate.com",
    name: "박규석",
    status: "승인",
    registrationDate: "2022-02-11",
    lastLogin: "2024-04-22",
    group: "Member",
    actions: "조회/수정",
  },
  {
    id: "seungheoni",
    nickname: "GaeGGul",
    email: "heoni88@gmail.com",
    name: "이승헌",
    status: "승인",
    registrationDate: "2022-02-11",
    lastLogin: "2023-10-04",
    group: "Member",
    actions: "조회/수정",
  },
  {
    id: "gygy05",
    nickname: "Shangks",
    email: "gygy05@naver.com",
    name: "임정균",
    status: "승인",
    registrationDate: "2022-02-11",
    lastLogin: "2024-04-09",
    group: "Member",
    actions: "조회/수정",
  },
  {
    id: "psh5131",
    nickname: "mnb",
    email: "shn8947@naver.com",
    name: "박세현",
    status: "승인",
    registrationDate: "2022-02-11",
    lastLogin: "2024-04-22",
    group: "Member",
    actions: "조회/수정",
  },
  {
    id: "choihesic",
    nickname: "Jeobji",
    email: "choihesic@naver.com",
    name: "최희식",
    status: "승인",
    registrationDate: "2022-02-11",
    lastLogin: "2024-04-21",
    group: "Member",
    actions: "조회/수정",
  },
  {
    id: "hijinhoon",
    nickname: "Developer",
    email: "hijunhoon@naver.com",
    name: "송진훈",
    status: "승인",
    registrationDate: "2022-02-11",
    lastLogin: "2024-04-28",
    group: "Member",
    actions: "조회/수정",
  },
  {
    id: "comic200123",
    nickname: "bebig",
    email: "comic200123@naver.com",
    name: "전민혁",
    status: "승인",
    registrationDate: "2022-02-11",
    lastLogin: "2024-04-23",
    group: "Member",
    actions: "조회/수정",
  },
  {
    id: "smart",
    nickname: "Smart",
    email: "ghdtor2@naver.com",
    name: "이대우",
    status: "승인",
    registrationDate: "2022-02-11",
    lastLogin: "2024-03-17",
    group: "관리그룹",
    actions: "조회/수정",
  },
  {
    id: "sungho05",
    nickname: "fOrU",
    email: "o1096625154@daum.net",
    name: "김성호",
    status: "승인",
    registrationDate: "2022-02-11",
    lastLogin: "2024-04-30",
    group: "관리그룹",
    actions: "조회/수정",
  },
  {
    id: "rudgjsl",
    nickname: "EaglE",
    email: "rudgjsl@nate.com",
    name: "정대겸",
    status: "승인",
    registrationDate: "2022-02-10",
    lastLogin: "2024-03-18",
    group: "Member",
    actions: "조회/수정",
  },
  {
    id: "soft",
    nickname: "Soft",
    email: "themedichi@hanmail.net",
    name: "박영균",
    status: "승인",
    registrationDate: "2022-02-10",
    lastLogin: "2023-01-03",
    group: "Member",
    actions: "조회/수정",
  },
  {
    id: "ting",
    nickname: "Ting",
    email: "show1007@naver.com",
    name: "이현준",
    status: "승인",
    registrationDate: "2022-02-09",
    lastLogin: "2024-04-16",
    group: "Member",
    actions: "조회/수정",
  },
  {
    id: "hon",
    nickname: "혼",
    email: "qoiiiop@naver.com",
    name: "박종훈",
    status: "승인",
    registrationDate: "2022-02-04",
    lastLogin: "2024-04-15",
    group: "Member",
    actions: "조회/수정",
  },
  {
    id: "nimsalsalyo",
    nickname: "ang",
    email: "allone_j@hanmail.net",
    name: "김지유",
    status: "승인",
    registrationDate: "2023-02-04",
    lastLogin: "2024-04-12",
    group: "Member",
    actions: "조회/수정",
  },
  {
    id: "kggkgbb",
    nickname: "NaNa",
    email: "sktt1_midas@naver.com",
    name: "김상현",
    status: "승인",
    registrationDate: "2023-01-17",
    lastLogin: "2024-04-29",
    group: "Member",
    actions: "조회/수정",
  },
  {
    id: "be_debruyne",
    nickname: "DeBruyne",
    email: "trust1702@naver.com",
    name: "김도윤",
    status: "승인",
    registrationDate: "2023-01-01",
    lastLogin: "2024-04-07",
    group: "Member",
    actions: "조회/수정",
  },
  {
    id: "pleanzer",
    nickname: "TOPGUN",
    email: "yourwishsc@gmail.com",
    name: "정영우",
    status: "승인",
    registrationDate: "2022-12-31",
    lastLogin: "2024-03-01",
    group: "Member",
    actions: "조회/수정",
  },
  {
    id: "movement",
    nickname: "movement",
    email: "tkwkwkfl124@naver.com",
    name: "박병규",
    status: "승인",
    registrationDate: "2022-12-29",
    lastLogin: "2024-03-07",
    group: "Member",
    actions: "조회/수정",
  },
  {
    id: "be_sugi",
    nickname: "sugi",
    email: "miller09@naver.com",
    name: "조민준",
    status: "승인",
    registrationDate: "2022-12-20",
    lastLogin: "2024-02-17",
    group: "Member",
    actions: "조회/수정",
  },
  {
    id: "ksmo5",
    nickname: "Promise",
    email: "sweetmilkb@naver.com",
    name: "김성민",
    status: "승인",
    registrationDate: "2022-12-08",
    lastLogin: "2023-07-25",
    group: "Member",
    actions: "조회/수정",
  },
  {
    id: "estjsm",
    nickname: "hankkukwan",
    email: "estjsm@hanmail.net",
    name: "전성민",
    status: "승인",
    registrationDate: "2022-12-07",
    lastLogin: "2024-04-08",
    group: "Member",
    actions: "조회/수정",
  },
  {
    id: "qkrwn1029",
    nickname: "inbong",
    email: "qkrwn1029@nate.con",
    name: "안영현",
    status: "승인",
    registrationDate: "2022-12-05",
    lastLogin: "2024-04-16",
    group: "Member",
    actions: "조회/수정",
  },
  {
    id: "miny21c",
    nickname: "JMT",
    email: "miny21c@naver.com",
    name: "김정민",
    status: "승인",
    registrationDate: "2022-12-03",
    lastLogin: "2024-04-22",
    group: "Member",
    actions: "조회/수정",
  },
  {
    id: "ddugi",
    nickname: "ddugi",
    email: "technical@hanmail.net",
    name: "김민기",
    status: "승인",
    registrationDate: "2022-10-03",
    lastLogin: "2023-10-09",
    group: "Member",
    actions: "조회/수정",
  },
  {
    id: "hanchi",
    nickname: "hanchi",
    email: "bjrsuo@nate.com",
    name: "한치훈",
    status: "승인",
    registrationDate: "2022-09-10",
    lastLogin: "2024-04-27",
    group: "Member",
    actions: "조회/수정",
  },
  {
    id: "mesis",
    nickname: "Mesis",
    email: "kwonjh1128@naver.com",
    name: "권장현",
    status: "승인",
    registrationDate: "2022-08-13",
    lastLogin: "2024-04-30",
    group: "Member",
    actions: "조회/수정",
  },
  {
    id: "csm2000",
    nickname: "COST",
    email: "csm-2000@hanmail.net",
    name: "차상명",
    status: "승인",
    registrationDate: "2022-08-09",
    lastLogin: "2024-04-28",
    group: "Member",
    actions: "조회/수정",
  },
  {
    id: "zerguser0909",
    nickname: "HI",
    email: "yeongjoon0008@gmail.com",
    name: "황영준",
    status: "승인",
    registrationDate: "2022-08-05",
    lastLogin: "2022-11-23",
    group: "Member",
    actions: "조회/수정",
  },
  {
    id: "leebh6619",
    nickname: "eByeong",
    email: "leebh6619@naver.com",
    name: "이병훈",
    status: "승인",
    registrationDate: "2022-07-30",
    lastLogin: "2024-04-30",
    group: "Member",
    actions: "조회/수정",
  },
  {
    id: "fatty",
    nickname: "Fatty",
    email: "bwhkdskstkwjf@naver.com",
    name: "김경태",
    status: "승인",
    registrationDate: "2022-07-30",
    lastLogin: "2024-04-17",
    group: "Member",
    actions: "조회/수정",
  },
  {
    id: "ruby23",
    nickname: "LYJ",
    email: "ruby2317@nate.com",
    name: "임영진",
    status: "승인",
    registrationDate: "2022-07-23",
    lastLogin: "2024-04-30",
    group: "Member",
    actions: "조회/수정",
  },
  {
    id: "beat",
    nickname: "AT",
    email: "wov423@naver.com",
    name: "정우성",
    status: "승인",
    registrationDate: "2022-07-23",
    lastLogin: "2024-03-31",
    group: "Member",
    actions: "조회/수정",
  },
  {
    id: "dywma123",
    nickname: "Cause",
    email: "leehaksung33@naver.com",
    name: "이학승",
    status: "승인",
    registrationDate: "2022-07-17",
    lastLogin: "2024-04-10",
    group: "Member",
    actions: "조회/수정",
  },
  {
    id: "wjdgus12",
    nickname: "Naerim",
    email: "yhg2027@naver.com",
    name: "양정현",
    status: "승인",
    registrationDate: "2022-07-04",
    lastLogin: "2024-04-18",
    group: "Member",
    actions: "조회/수정",
  },
  {
    id: "rla8013",
    nickname: "Quiet",
    email: "yoonbae94@naver.com",
    name: "김윤배",
    status: "승인",
    registrationDate: "2022-06-26",
    lastLogin: "2024-04-30",
    group: "관리그룹",
    actions: "조회/수정",
  },
  {
    id: "ssibom",
    nickname: "KOEUN",
    email: "jhjahmo@naver.com",
    name: "조영철",
    status: "승인",
    registrationDate: "2022-06-26",
    lastLogin: "2024-04-12",
    group: "Member",
    actions: "조회/수정",
  },
  {
    id: "uya0001",
    nickname: "song",
    email: "beataroundthebush@naver.com",
    name: "송지섭",
    status: "승인",
    registrationDate: "2022-06-25",
    lastLogin: "2024-04-17",
    group: "Member",
    actions: "조회/수정",
  },
  {
    id: "pms7454",
    nickname: "Speed",
    email: "pms7454@hanmail.net",
    name: "박민수",
    status: "승인",
    registrationDate: "2022-06-25",
    lastLogin: "2024-04-12",
    group: "Member",
    actions: "조회/수정",
  },
  {
    id: "lyovne",
    nickname: "Dulgi",
    email: "zinobbb@naver.com",
    name: "배진호",
    status: "승인",
    registrationDate: "2022-06-25",
    lastLogin: "2024-04-16",
    group: "Member",
    actions: "조회/수정",
  },
  {
    id: "djwh60",
    nickname: "Careful",
    email: "djwh60@naver.com",
    name: "조덕제",
    status: "승인",
    registrationDate: "2022-06-23",
    lastLogin: "2024-04-28",
    group: "Member",
    actions: "조회/수정",
  },
  {
    id: "hanbum43",
    nickname: "Square",
    email: "h951221@naver.com",
    name: "한범수",
    status: "승인",
    registrationDate: "2022-06-20",
    lastLogin: "2023-03-20",
    group: "Member",
    actions: "조회/수정",
  },
  {
    id: "fzc_rebellious",
    nickname: "Ruin",
    email: "koreaboy91@hamail.net",
    name: "이승호",
    status: "승인",
    registrationDate: "2022-05-24",
    lastLogin: "2024-04-30",
    group: "관리그룹",
    actions: "조회/수정",
  },
  {
    id: "wldus123",
    nickname: "Mangnani",
    email: "qkddnf550444@gmail.com",
    name: "이지연",
    status: "승인",
    registrationDate: "2022-05-06",
    lastLogin: "2024-03-29",
    group: "Member",
    actions: "조회/수정",
  },
  {
    id: "tjdgus452",
    nickname: "chojja",
    email: "tjdgus1248@nate.com",
    name: "주성현",
    status: "승인",
    registrationDate: "2022-04-08",
    lastLogin: "2024-02-24",
    group: "Member",
    actions: "조회/수정",
  },
  {
    id: "dlacksdn98",
    nickname: "omgYubin",
    email: "chanwoofly@naver.com",
    name: "임찬우",
    status: "승인",
    registrationDate: "2022-04-06",
    lastLogin: "2024-04-30",
    group: "Member",
    actions: "조회/수정",
  },
  {
    id: "breakfast7",
    nickname: "bugaboo",
    email: "breakfast777@naver.com",
    name: "정다운",
    status: "승인",
    registrationDate: "2022-04-05",
    lastLogin: "2024-04-30",
    group: "Member",
    actions: "조회/수정",
  },
  {
    id: "to_k",
    nickname: "to..k",
    email: "hs20110740@hyosung.com",
    name: "김동근",
    status: "승인",
    registrationDate: "2022-04-05",
    lastLogin: "2023-10-25",
    group: "Member",
    actions: "조회/수정",
  },
  {
    id: "sori9002",
    nickname: "Azure",
    email: "gwang9382@naver.com",
    name: "송광식",
    status: "승인",
    registrationDate: "2022-03-21",
    lastLogin: "2024-04-30",
    group: "Member",
    actions: "조회/수정",
  },
  {
    id: "hope",
    nickname: "Hope",
    email: "narasp@naver.com",
    name: "이상필",
    status: "승인",
    registrationDate: "2022-03-12",
    lastLogin: "2024-04-30",
    group: "Member",
    actions: "조회/수정",
  },
  {
    id: "allfree",
    nickname: "allfree",
    email: "dlrhkstjq5@naver.com",
    name: "이관섭",
    status: "승인",
    registrationDate: "2022-03-07",
    lastLogin: "2024-04-13",
    group: "Member",
    actions: "조회/수정",
  },
  {
    id: "cduckku",
    nickname: "dduk99",
    email: "cduckku1@naver.com",
    name: "최덕규",
    status: "승인",
    registrationDate: "2022-03-04",
    lastLogin: "2024-04-24",
    group: "Member",
    actions: "조회/수정",
  },
  {
    id: "mannerplayer",
    nickname: "Man",
    email: "jjun96@gmail.com",
    name: "신준열",
    status: "승인",
    registrationDate: "2022-03-03",
    lastLogin: "2023-04-21",
    group: "Member",
    actions: "조회/수정",
  },
  {
    id: "muzf",
    nickname: "qqwe",
    email: "songdatji@naver.com",
    name: "송상",
    status: "승인",
    registrationDate: "2024-04-21",
    lastLogin: "2024-04-23",
    group: "Member",
    actions: "조회/수정",
  },
  {
    id: "dydgnl17",
    nickname: "taxer",
    email: "fblk093@naver.com",
    name: "김용휘",
    status: "승인",
    registrationDate: "2024-04-14",
    lastLogin: "2024-04-24",
    group: "Member",
    actions: "조회/수정",
  },
  {
    id: "gravity",
    nickname: "Gravity",
    email: "jjr961104@gmail.com",
    name: "정재령",
    status: "승인",
    registrationDate: "2024-04-13",
    lastLogin: "2024-04-29",
    group: "Member",
    actions: "조회/수정",
  },
  {
    id: "dark",
    nickname: "Dark",
    email: "beevz@naver.com",
    name: "김민성",
    status: "승인",
    registrationDate: "2024-04-11",
    lastLogin: "2024-04-30",
    group: "Member",
    actions: "조회/수정",
  },
  {
    id: "cnckdgh24",
    nickname: "lonely",
    email: "ssa2nose2424@gmail.com",
    name: "임수성",
    status: "승인",
    registrationDate: "2024-04-10",
    lastLogin: "2024-04-15",
    group: "Member",
    actions: "조회/수정",
  },
  {
    id: "eldk09",
    nickname: "zz",
    email: "dlstk21@naver.com",
    name: "이주형",
    status: "승인",
    registrationDate: "2024-04-09",
    lastLogin: "2024-04-29",
    group: "Member",
    actions: "조회/수정",
  },
  {
    id: "hazlelatte",
    nickname: "hazlelatte",
    email: "dlcjfgh86@naver.com",
    name: "이철호",
    status: "승인",
    registrationDate: "2024-04-09",
    lastLogin: "2024-04-09",
    group: "Member",
    actions: "조회/수정",
  },
  {
    id: "seok123",
    nickname: "파라노이즈",
    email: "law7890zxcv@naver.com",
    name: "김석현",
    status: "승인",
    registrationDate: "2024-03-31",
    lastLogin: "2024-04-15",
    group: "Member",
    actions: "조회/수정",
  },
  {
    id: "hayun0415",
    nickname: "hayun",
    email: "eogkrry33@naver.com",
    name: "강하윤",
    status: "승인",
    registrationDate: "2024-03-28",
    lastLogin: "2024-04-30",
    group: "Member",
    actions: "조회/수정",
  },
  {
    id: "swdh",
    nickname: "sai",
    email: "swdh1@naver.com",
    name: "선우도현",
    status: "승인",
    registrationDate: "2024-02-23",
    lastLogin: "2024-03-08",
    group: "Member",
    actions: "조회/수정",
  },
  {
    id: "ghst12",
    nickname: "Poo",
    email: "friend9412@naver.com",
    name: "홍상준",
    status: "승인",
    registrationDate: "2024-02-14",
    lastLogin: "2024-03-31",
    group: "Member",
    actions: "조회/수정",
  },
  {
    id: "janghoman",
    nickname: "Ssam",
    email: "bestworkvina@gmail.com",
    name: "문장호",
    status: "승인",
    registrationDate: "2024-02-01",
    lastLogin: "2024-02-01",
    group: "Guest",
    actions: "조회/수정",
  },
  {
    id: "miniangma",
    nickname: "miniangma",
    email: "monster_men@naver.com",
    name: "이창기",
    status: "승인",
    registrationDate: "2024-01-07",
    lastLogin: "2024-04-17",
    group: "Member",
    actions: "조회/수정",
  },
  {
    id: "light",
    nickname: "Light",
    email: "bliss1993@naver.com",
    name: "홍상범",
    status: "승인",
    registrationDate: "2023-12-30",
    lastLogin: "2024-03-03",
    group: "Member",
    actions: "조회/수정",
  },
  {
    id: "korhjs5493",
    nickname: "sinma",
    email: "korhjs5493@gmail.com",
    name: "황재성",
    status: "승인",
    registrationDate: "2023-12-29",
    lastLogin: "2024-02-05",
    group: "Member",
    actions: "조회/수정",
  },
  {
    id: "kdhee0429",
    nickname: "Delluna",
    email: "kdhee0429@naver.com",
    name: "김동희",
    status: "승인",
    registrationDate: "2023-12-15",
    lastLogin: "2024-04-30",
    group: "Member",
    actions: "조회/수정",
  },
  {
    id: "ambasa",
    nickname: "ambasa",
    email: "edq1w@naver.com",
    name: "권민철",
    status: "승인",
    registrationDate: "2023-12-10",
    lastLogin: "2023-12-23",
    group: "Member",
    actions: "조회/수정",
  },
  {
    id: "sw4830",
    nickname: "Classic",
    email: "sungwoo483@naver.com",
    name: "홍성우",
    status: "승인",
    registrationDate: "2023-12-10",
    lastLogin: "2023-12-21",
    group: "Member",
    actions: "조회/수정",
  },
  {
    id: "cokiert301",
    nickname: "4Vulture",
    email: "cokier301@naver.com",
    name: "이청솔",
    status: "승인",
    registrationDate: "2023-11-07",
    lastLogin: "2024-03-08",
    group: "Member",
    actions: "조회/수정",
  },
  {
    id: "kus2972",
    nickname: "Astell",
    email: "kes9003@daum.net",
    name: "김은성",
    status: "승인",
    registrationDate: "2023-11-04",
    lastLogin: "2024-04-30",
    group: "Member",
    actions: "조회/수정",
  },
  {
    id: "rlghksdl963",
    nickname: "CU",
    email: "hamster5960@naver.com",
    name: "김기환",
    status: "승인",
    registrationDate: "2023-10-09",
    lastLogin: "2023-10-13",
    group: "Member",
    actions: "조회/수정",
  },
  {
    id: "k1146",
    nickname: "Captain",
    email: "kimhs1146@naver.com",
    name: "김현식",
    status: "승인",
    registrationDate: "2023-09-30",
    lastLogin: "2024-02-22",
    group: "Member",
    actions: "조회/수정",
  },
  {
    id: "dnxotlr_12",
    nickname: "Gotz",
    email: "ka1492@naver.com",
    name: "김영준",
    status: "승인",
    registrationDate: "2023-09-27",
    lastLogin: "2024-02-18",
    group: "Member",
    actions: "조회/수정",
  },
  {
    id: "rkffkr",
    nickname: "갈락티코",
    email: "c@c.com",
    name: "갈락티코",
    status: "승인",
    registrationDate: "2023-09-25",
    lastLogin: "2024-01-02",
    group: "관리그룹",
    actions: "조회/수정",
  },
  {
    id: "qjzlddja",
    nickname: "버킹엄",
    email: "b@a.com",
    name: "버킹엄",
    status: "승인",
    registrationDate: "2023-09-25",
    lastLogin: "2023-12-04",
    group: "Member",
    actions: "조회/수정",
  },
  {
    id: "one",
    nickname: "원",
    email: "a@a.com",
    name: "원",
    status: "승인",
    registrationDate: "2023-09-25",
    lastLogin: "2023-09-26",
    group: "Member",
    actions: "조회/수정",
  },
  {
    id: "dlkdalsehs",
    nickname: "이창민",
    email: "dlkdalsehs1@naver.com",
    name: "이창민",
    status: "승인",
    registrationDate: "2023-08-25",
    lastLogin: "2024-04-14",
    group: "Member",
    actions: "조회/수정",
  },
  {
    id: "terran",
    nickname: "Terran",
    email: "pj01306@naver.com",
    name: "유기현",
    status: "승인",
    registrationDate: "2023-07-22",
    lastLogin: "2024-03-04",
    group: "Member",
    actions: "조회/수정",
  },
  {
    id: "panda",
    nickname: "panda",
    email: "lunis94@naver.com",
    name: "김응주",
    status: "승인",
    registrationDate: "2023-07-21",
    lastLogin: "2024-03-05",
    group: "Member",
    actions: "조회/수정",
  },
  {
    id: "wndud9466",
    nickname: "Tako",
    email: "ajdcjd1004@naver.com",
    name: "윤주영",
    status: "승인",
    registrationDate: "2023-05-18",
    lastLogin: "2024-04-30",
    group: "Member",
    actions: "조회/수정",
  },
  {
    id: "eunice",
    nickname: "Eunice",
    email: "nexeunice@naver.com",
    name: "최상민",
    status: "승인",
    registrationDate: "2023-05-12",
    lastLogin: "2023-10-13",
    group: "Member",
    actions: "조회/수정",
  },
  {
    id: "chl5725",
    nickname: "chl5725",
    email: "dnwjddkfo@naver.com",
    name: "최창주",
    status: "승인",
    registrationDate: "2023-05-07",
    lastLogin: "2023-07-11",
    group: "Member",
    actions: "조회/수정",
  },
  {
    id: "leejuzzang",
    nickname: "plugpower",
    email: "leejuzzang@hanmail.net",
    name: "이종욱",
    status: "승인",
    registrationDate: "2023-03-07",
    lastLogin: "2024-04-30",
    group: "Member",
    actions: "조회/수정",
  },
  {
    id: "estrogen87",
    nickname: "Cervix",
    email: "strangler1@naver.com",
    name: "이태영",
    status: "승인",
    registrationDate: "2023-03-06",
    lastLogin: "2024-02-22",
    group: "Member",
    actions: "조회/수정",
  },
  {
    id: "hon1",
    nickname: "hOn",
    email: "hon@1.com",
    name: "종훈",
    status: "승인",
    registrationDate: "2023-03-04",
    lastLogin: "2023-07-10",
    group: "관리그룹",
    actions: "조회/수정",
  },
  {
    id: "paduk",
    nickname: "Paduk",
    email: "wazzup@nate.com",
    name: "김태훈",
    status: "승인",
    registrationDate: "2023-02-20",
    lastLogin: "2024-04-18",
    group: "Member",
    actions: "조회/수정",
  },
  {
    id: "t5519864",
    nickname: "Ark",
    email: "15519864@naver.com",
    name: "권순주",
    status: "승인",
    registrationDate: "2023-02-16",
    lastLogin: "2024-04-26",
    group: "Member",
    actions: "조회/수정",
  },
  {
    id: "hyunsm0917",
    nickname: "Arin",
    email: "meddugi2529@naver.com",
    name: "현승민",
    status: "승인",
    registrationDate: "2023-02-08",
    lastLogin: "2024-04-12",
    group: "Member",
    actions: "조회/수정",
  },
];

export const pointMember = [
  { nickname: "fOrU", points: 232768 },
  { nickname: "hanchi", points: 129321 },
  { nickname: "AT", points: 60408 },
  { nickname: "Ark", points: 54835 },
  { nickname: "COST", points: 39202 },
  { nickname: "YOASOBI", points: 37845 },
  { nickname: "원", points: 36215 },
  { nickname: "Naerim", points: 35005 },
  { nickname: "allfree", points: 32278 },
  { nickname: "버킹엄", points: 27645 },
  { nickname: "GaeGGul", points: 23968 },
  { nickname: "bebig", points: 23444 },
  { nickname: "uNiQue", points: 23115 },
  { nickname: "JB", points: 22903 },
  { nickname: "Hope", points: 22551 },
  { nickname: "miniangma", points: 21787 },
  { nickname: "KIMKOEUN", points: 21596 },
  { nickname: "sinma", points: 21060 },
  { nickname: "Developer", points: 20427 },
  { nickname: "Jeobji", points: 20093 },
  { nickname: "Azure", points: 19904 },
  { nickname: "inbong", points: 19828 },
  { nickname: "Ruin", points: 18776 },
  { nickname: "갈락티코", points: 18490 },
  { nickname: "song", points: 17760 },
  { nickname: "mnb", points: 17077 },
  { nickname: "Gotz", points: 17044 },
  { nickname: "Light", points: 16702 },
  { nickname: "Josh", points: 16018 },
  { nickname: "Classic", points: 15951 },
  { nickname: "bugaboo", points: 14465 },
  { nickname: "OnSi", points: 14272 },
  { nickname: "dduk99", points: 13841 },
  { nickname: "비Zzz", points: 13750 },
  { nickname: "hOn", points: 13470 },
  { nickname: "LYJ", points: 13383 },
  { nickname: "Laufe", points: 13056 },
  { nickname: "SnOw", points: 13049 },
  { nickname: "Careful", points: 12816 },
  { nickname: "NaNa", points: 11547 },
  { nickname: "hankkukwan", points: 11270 },
  { nickname: "movement", points: 11157 },
  { nickname: "soo", points: 11156 },
  { nickname: "Astell", points: 10754 },
  { nickname: "Promise", points: 10651 },
  { nickname: "Quiet", points: 10540 },
  { nickname: "Shangks", points: 10330 },
  { nickname: "Mesis", points: 10072 },
  { nickname: "Promy", points: 9561 },
  { nickname: "Medic", points: 9526 },
  { nickname: "to..k", points: 9469 },
  { nickname: "Dulgi", points: 9318 },
  { nickname: "BFatty", points: 9188 },
  { nickname: "eByeong", points: 9186 },
  { nickname: "4Vulture", points: 9151 },
  { nickname: "omgYubin", points: 8931 },
  { nickname: "chojja", points: 8761 },
  { nickname: "Smart", points: 8493 },
  { nickname: "JMT", points: 8274 },
  { nickname: "Captain", points: 7574 },
  { nickname: "Politan", points: 7546 },
  { nickname: "ang", points: 7401 },
  { nickname: "DeBruyne", points: 7383 },
  { nickname: "plugpower", points: 6873 },
  { nickname: "Cause", points: 5947 },
  { nickname: "Delluna", points: 5365 },
  { nickname: "YODAKING", points: 5269 },
  { nickname: "BEaglE", points: 5083 },
  { nickname: "Square", points: 5023 },
  { nickname: "Mangnani", points: 4670 },
  { nickname: "Eunice", points: 4642 },
  { nickname: "sugi", points: 4631 },
  { nickname: "Tako", points: 4407 },
  { nickname: "ClanBeSoft", points: 4337 },
  { nickname: "TOPGUN", points: 4294 },
  { nickname: "Marine", points: 4050 },
  { nickname: "Cervix", points: 4043 },
  { nickname: "이창민", points: 4035 },
  { nickname: "Terran", points: 4004 },
  { nickname: "Speed", points: 3919 },
  { nickname: "Panda", points: 3846 },
  { nickname: "hayun", points: 3550 },
  { nickname: "HI", points: 3235 },
  { nickname: "파라노이즈", points: 3200 },
  { nickname: "Poo", points: 3011 },
  { nickname: "zz", points: 3000 },
  { nickname: "taxer", points: 2700 },
  { nickname: "lonely", points: 2630 },
  { nickname: "Gravity", points: 2630 },
  { nickname: "sai", points: 2600 },
  { nickname: "qqwe", points: 2600 },
  { nickname: "chl5725", points: 2530 },
  { nickname: "Dark", points: 2495 },
  { nickname: "needmonkey", points: 2400 },
  { nickname: "hazlelatte", points: 2400 },
  { nickname: "Apple", points: 2372 },
  { nickname: "Jerry", points: 2022 },
  { nickname: "추쒸님", points: 2024 },
  { nickname: "혼", points: 2022 },
  { nickname: "test", points: 2022 },
  { nickname: "Paduk", points: 2023 },
  { nickname: "ddugi", points: 2022 },
  { nickname: "Gisa", points: 2022 },
  { nickname: "Man", points: 2022 },
  { nickname: "WanJa", points: 2022 },
  { nickname: "admin", points: 2022 },
  { nickname: "Ting", points: 2022 },
  { nickname: "Arin", points: 2023 },
  { nickname: "CU", points: 2023 },
  { nickname: "ambasa", points: 2023 },
  { nickname: "Ssam", points: 2024 },
  { nickname: "12121212", points: 2022 },
  { nickname: "GamJa", points: 2022 },
];

export const aligns = [
  {
    label: "기본",
    value: "기본",
    description: "기본기준으로 게시글을 정렬합니다.",
  },
  {
    label: "날짜",
    value: "날짜",
    description: "게시날짜 순으로 게시글을 정렬합니다.",
  },
  {
    label: "조회수",
    value: "조회수",
    description: "조회수 순으로 게시글을 정렬합니다.",
  },
];

export const tabs = [
  {
    id: "photos",
    label: "Photos",
    content:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
  },
  {
    id: "music",
    label: "Music",
    content:
      "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
  },
  {
    id: "videos",
    label: "Videos",
    content:
      "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
];

export const searchOption = [
  {
    label: "제목",
    value: "제목",
    description: "제목기준으로 게시글을 검색합니다.",
  },
  {
    label: "내용",
    value: "내용",
    description: "내용 순으로 게시글을 검색합니다.",
  },
  {
    label: "닉네임",
    value: "닉네임",
    description: "닉네임 순으로 게시글을 검색합니다.",
  },
];

export const posts = [
  {
    number: "공지",
    title: "2024, 3월, 3일 공지사항",
    author: "forU",
    date: "24.03.03.",
    views: "68",
  },
  {
    number: "공지",
    title: "2.13 공지사항",
    author: "forU",
    date: "24.02.13.",
    views: "80",
  },
  {
    number: "공지",
    title: "12.16 영업진 회의 공지사항",
    author: "forU",
    date: "22.12.18.",
    views: "290",
  },
  {
    number: "공지",
    title: "06.25 영업진 회의 공지사항",
    author: "JPAPA",
    date: "22.06.27.",
    views: "348",
  },
  {
    number: "34",
    title: "프로모션 진행중",
    author: "hOn",
    date: "22.03.25.",
    views: "106",
  },
  {
    number: "33",
    title: "3.17 영업진회의",
    author: "hOn",
    date: "22.03.18.",
    views: "77",
  },
];

export const columns = [
  { name: "STATUS", uid: "status" },
  { name: "NAME", uid: "name" },
  { name: "ROLE", uid: "role" },
];

export const mobilecolumns = [
  { name: "STATUS", uid: "status" },
  { name: "NAME", uid: "name" },
];

export const headerDummy = {
  buttonTitle: "더미메뉴",
  menuItems: [
    {
      title: "더미1번",
      description: "더미임",
      icon: "scale",
    },
    {
      title: "더미2번",
      description: "더미임",
      icon: "flash",
    },
    {
      title: "더미3번",
      description: "더미임",
      icon: "server",
    },
  ],
};

export const headerCLANBE = {
  buttonTitle: "CLANBE",
  menuItems: [
    {
      title: "공지 사항",
      description: "Be클랜의 필수공지사항을 확인 할 수 있습니다.",
      icon: "scale",
      href: "/clanbe/notices",
    },
    {
      title: "클랜 일정",
      description:
        "클랜리그/이벤트 등의 모든 일정을 달력을 통해 확인 할 수 있습니다.",
      icon: "activity",
      href: "/clanbe/schedule",
    },
    {
      title: "클랜원 명단",
      description: "전체 클랜원들의 명단 및 운영진 명단을 확인 할 수 있습니다.",
      icon: "flash",
      href: "/clanbe/members",
    },
    {
      title: "클랜 규정",
      description:
        "클랜원 활동에 필요한 필수규칙 및 운영방침을 확인 할 수 있습니다.",
      icon: "server",
      href: "/clanbe/rules",
    },
    // {
    //   title: "티어배정",
    //   description: "티어배정신청 및 티어배정결과를 확인하는 페이지",
    //   icon: "scale",
    //   href: "/clanbe/tear",
    // },
    {
      title: "클랜 후원",
      description: "클랜의 활동에 필요한 후원자금에 관련된 게시판 입니다.",
      icon: "user",
      href: "/clanbe/support",
    },
  ],
};

export const headerCOMMUNITY = {
  buttonTitle: "커뮤니티",
  menuItems: [
    {
      title: "전체글보기",
      description: "전체 게시글을 확인할 수 있습니다.",
      icon: "scale",
      href: "/community/allposts",
    },
    {
      title: "자유게시판",
      description: "자유주제 게시글을 확인할 수 있습니다.",
      icon: "flash",
      href: "/community/forum",
    },
    {
      title: "가입인사",
      description: "새로운 멤버들의 가입인사를 확인할 수 있습니다.",
      icon: "flash",
      href: "/community/introduce",
    },
    {
      title: "건의사항",
      description: "클랜/홈페이지 건의사항을 확인할 수 있습니다.",
      icon: "flash",
      href: "/community/feedback",
    },
    {
      title: "전략전술",
      description: "전략전술을 공유하는 게시판입니다.",
      icon: "server",
      href: "/community/tactics",
    },
    // {
    //   title: "출석체크",
    //   description: "출석체크를 위한 게시판입니다.",
    //   icon: "user",
    //   href: "/community/dailycheckin",
    // },
  ],
};

export const headerBELO = {
  buttonTitle: "BELO",
  menuItems: [
    {
      title: "BELO란?",
      description: "BELO 시스템/규정 소개",
      icon: "scale",
      href: "/belo/introduce",
    },
    {
      title: "BELO 선수기록",
      description: "BELO 시즌 선수기록",
      icon: "server",
      href: "/belo/beloseason",
    },
    {
      title: "BELO 경기기록",
      description: "BELO 시즌 경기기록",
      icon: "server",
      href: "/belo/history",
    },
  ],
};

export const headerLEAGUE = {
  buttonTitle: "리그",
  menuItems: [
    {
      title: "VOD 다시보기",
      description:
        "프로리그 / 외부경기 / 이벤트 등의 경기를 다시보기 할 수 있습니다.",
      icon: "server",
      href: "/league/vod",
    },
    {
      title: "랭킹전",
      description: "클랜 내부 랭킹전 기록을 등록/열람 할 수 있습니다.",
      icon: "scale",
      href: "/league/ranking",
    },
    {
      title: "EVENT",
      description: "클랜 내부 이벤트 게시물을 확인 할 수 있습니다.",
      icon: "flash",
      href: "/league/event",
    },
    {
      title: "외부리그",
      description: "클랜 외부 리그 경기기록을 확인 할 수 있습니다.",
      icon: "server",
      href: "/league/opponent",
    },
    {
      title: "끝장전",
      description: "클랜 내부 끝장전 기록을 등록/열람 할 수 있습니다.",
      icon: "server",
      href: "/league/versus",
    },
  ],
};

export const headerPOINT = {
  buttonTitle: "포인트",
  menuItems: [
    {
      title: "포인트규정",
      description: "더미임",
      icon: "scale",
      href: "/point/rules",
    },
    {
      title: "포인트랭킹",
      description: "더미임",
      icon: "flash",
      href: "/point/ranking",
    },
    // {
    //   title: "가위바위보",
    //   description: "더미임",
    //   icon: "server",
    //   href: "/point/rps",
    // },
    // {
    //   title: "로또복권",
    //   description: "더미임",
    //   icon: "server",
    //   href: "/point/lotto",
    // },
    // {
    //   title: "포인트 배팅",
    //   description: "더미임",
    //   icon: "server",
    //   href: "/point/betting",
    // },
  ],
};

export const headerPROLEAGUE = {
  buttonTitle: "프로리그",
  menuItems: [
    {
      title: "프로리그 공지",
      description: "프로리그 관련 소식을 다루는 게시판 입니다.",
      icon: "scale",
      href: "/proleague/notice",
    },
    {
      title: "순위표 / 일정",
      description: "팀 전체의 순위기록과 일정을 다루는 페이지 입니다.",
      icon: "server",
      href: "/proleague/schedule",
    },
    {
      title: "팀 로스터",
      description: "팀 로스터를 확인 및 관리 하는 페이지 입니다.",
      icon: "server",
      href: "/proleague/team",
    },
    // {
    //   title: "프로리그 드래프트",
    //   description:
    //     "프로리그 진행을 위한 드래프트 기능을 담당하는 페이지 입니다.",
    //   icon: "flash",
    //   href: "/PROLEAGUE/draft",
    // },
  ],
};
